set background=dark
set number
set autoindent
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smarttab
set cursorline
set incsearch
set hlsearch
set nocompatible
set encoding=UTF-8
